### ISSUE TITLE
Practica Back End Cafe Huerto

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-back-end-cafe-huerto#2]
[Practica de Login para Back-end_Edwin, Alexis, Ivan, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-cafe-huerto/files/6548366/Practica.de.Login.para.Back-end_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen Trabajo: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
